SET MAINTENANCE_WORK_MEM="50GB";

CREATE INDEX VARIANT_BIN_INDEX ON NIAGADS.Variant USING GIST(BIN_INDEX); 
CREATE INDEX VARIANT_METASEQ_LEFT50 ON NIAGADS.Variant(LEFT(metaseq_id, 50));
CREATE INDEX VARIANT_REFSNP_ID ON NIAGADS.Variant(ref_snp_id);
CREATE INDEX VARIANT_GIN_ANNOTATION ON NIAGADS.Variant USING GIN (annotation jsonb_path_ops);
CREATE INDEX VARIANT_POSITION ON NIAGADS.Variant (position);

CREATE INDEX VARIANT_CLUSTER ON NIAGADS.Variant(chromosome, POSITION);
CREATE INDEX VARIANT_ROW_ALG_ID ON NIAGADS.Variant (row_alg_invocation_id); -- for unloading


