SET maintenance_work_mem="100GB";
SET max_parallel_maintenance_workers TO 8;
SHOW maintenance_work_mem;
SHOW max_parallel_maintenance_workers;

/*
-- DROP INDEX Results.GWAS_RESULT_VRPK;
DROP INDEX Results.GWAS_RESULT_NL10P;
DROP INDEX Results.GWAS_RESULT_GWS;
DROP INDEX Results.GWAS_RESULT_RELAXED_GWS;
DROP INDEX Results.GWAS_RESULT_FILTERED_GWS;
DROP INDEX Results.GWAS_RESULT_VRPK_GWS;
DROP INDEX Results.GWAS_RESULT_VRPK_RELAXED_GWS;
-- DROP INDEX Results.GWAS_RESULT_BIN_INDEX;
DROP INDEX Results.GWAS_RESULT_LOOKUP;
-- DROP INDEX GWAS_RESULT_PER_TRACK_LOC;
*/

VACUUM (ANALYZE, VERBOSE) Results.VariantGWAS;

CREATE INDEX GWAS_RESULT_VRPK ON Results.VariantGWAS (VARIANT_RECORD_PRIMARY_KEY);

CREATE INDEX GWAS_RESULT_NL10P ON Results.VariantGWAS(NEG_LOG10_PVALUE DESC);

CREATE INDEX GWAS_RESULT_DATASET_GWS ON Results.VariantGWAS(PROTOCOL_APP_NODE_ID, NEG_LOG10_PVALUE DESC)
       WHERE neg_log10_pvalue >=  (-1 * log(10, 5e-8)); --5e-8

CREATE INDEX GWAS_RESULT_DATASET_RELAXED_GWS ON Results.VariantGWAS(PROTOCOL_APP_NODE_ID, NEG_LOG10_PVALUE DESC)
       WHERE neg_log10_pvalue >=  3.0;

CREATE INDEX GWAS_RESULT_DATASET_FILTERED_GWS ON Results.VariantGWAS(PROTOCOL_APP_NODE_ID, NEG_LOG10_PVALUE DESC) WHERE neg_log10_pvalue >  (-1 * log(10, 0.5));

/* CREATE INDEX GWAS_RESULT_VRPK_GWS ON Results.VariantGWAS(VARIANT_RECORD_PRIMARY_KEY, NEG_LOG10_PVALUE DESC) 
       WHERE neg_log10_pvalue >=  (-1 * log(10, 5e-8)); --5e-8 */

/* CREATE INDEX GWAS_RESULT_VRPK_RELAXED_GWS ON Results.VariantGWAS(VARIANT_RECORD_PRIMARY_KEY, NEG_LOG10_PVALUE DESC) 
       WHERE neg_log10_pvalue >= 3.0; */

CREATE INDEX GWAS_RESULT_BIN_INDEX ON Results.VariantGWAS USING GIST(BIN_INDEX);

--CREATE INDEX GWAS_RESULT_LOOKUP ON Results.VariantGWAS(PROTOCOL_APP_NODE_ID,(split_part(bin_index::text, '.', 1)),NEG_LOG10_PVALUE,VARIANT_RECORD_PRIMARY_KEY) WHERE neg_log10_pvalue >= 3.0;

CREATE INDEX GWAS_RESULT_PER_TRACK_LOC ON Results.VariantGWAS USING GIST(protocol_app_node_id, bin_index, (split_part(VARIANT_RECORD_PRIMARY_KEY, ':', 2)::BIGINT));


CREATE INDEX GWAS_RESULT_POSITION ON Results.VariantGWAS((split_part(VARIANT_RECORD_PRIMARY_KEY, ':', 2)::BIGINT);

