SET maintenance_work_mem="30GB";
SET max_parallel_maintenance_workers TO 8;
SHOW maintenance_work_mem;
SHOW max_parallel_maintenance_workers;

/*
-- DROP INDEX Results.GWAS_RESULT_VRPK;
DROP INDEX Results.GWAS_RESULT_NL10P;
DROP INDEX Results.GWAS_RESULT_GWS;
DROP INDEX Results.GWAS_RESULT_RELAXED_GWS;
DROP INDEX Results.GWAS_RESULT_FILTERED_GWS;
DROP INDEX Results.GWAS_RESULT_VRPK_GWS;
DROP INDEX Results.GWAS_RESULT_VRPK_RELAXED_GWS;
-- DROP INDEX Results.GWAS_RESULT_BIN_INDEX;
DROP INDEX Results.GWAS_RESULT_LOOKUP;
-- DROP INDEX GWAS_RESULT_PER_TRACK_LOC;
*/

CREATE INDEX GWAS_RESULT_PAN_BRIN ON Results.VariantGWAS USING BRIN(PROTOCOL_APP_NODE_ID);

CREATE INDEX GWAS_RESULT_UNDO ON Results.VariantGWAS (row_alg_invocation_id);

--CREATE INDEX GWAS_RESULT_VRPK ON Results.VariantGWAS(VARIANT_RECORD_PRIMARY_KEY);

CREATE INDEX GWAS_RESULT_VRPK_NL10P ON Results.VariantGWAS(VARIANT_RECORD_PRIMARY_KEY, NEG_LOG10_PVALUE DESC);
    WHERE neg_log10_pvalue >= 3.0;
CREATE INDEX GWAS_RESULT_PAN_NL10P ON Results.VariantGWAS(PROTOCOL_APP_NODE_ID, NEG_LOG10_PVALUE DESC)
    WHERE neg_log10_pvalue >=  3.0; 

CREATE INDEX GWAS_RESULT_BIN_INDEX ON Results.VariantGWAS USING GIST(BIN_INDEX);

VACUUM (ANALYZE, VERBOSE) Results.VariantGWAS;