CREATE INDEX GWAS_RESULT_VRPK ON Results.VariantGWAS (VARIANT_RECORD_PRIMARY_KEY);

CREATE INDEX GWAS_RESULT_NL10P ON Results.VariantGWAS(NEG_LOG10_PVALUE DESC);

CREATE INDEX GWAS_RESULT_GWS ON Results.VariantGWAS(NEG_LOG10_PVALUE DESC)
       WHERE neg_log10_pvalue >=  (-1 * log(10, 5e-8)); --5e-8

CREATE INDEX GWAS_RESULT_RELAXED_GWS ON Results.VariantGWAS(NEG_LOG10_PVALUE DESC)
       WHERE neg_log10_pvalue >=  3.0;

CREATE INDEX GWAS_RESULT_VRPK_GWS ON Results.VariantGWAS(VARIANT_RECORD_PRIMARY_KEY, NEG_LOG10_PVALUE DESC) 
       WHERE neg_log10_pvalue >=  (-1 * log(10, 5e-8)); --5e-8

CREATE INDEX GWAS_RESULT_VRPK_RELAXED_GWS ON Results.VariantGWAS(VARIANT_RECORD_PRIMARY_KEY, NEG_LOG10_PVALUE DESC) 
       WHERE neg_log10_pvalue >= 3.0;

CREATE INDEX GWAS_RESULT_BIN_INDEX ON Results.VariantGWAS USING GIST(BIN_INDEX);

CREATE INDEX GWAS_RESULT_LOOKUP ON Results.VariantGWAS(PROTOCOL_APP_NODE_ID,VARIANT_RECORD_PRIMARY_KEY,NEG_LOG10_PVALUE,PVALUE_DISPLAY);

CREATE INDEX GWAS_RESULT_POSITION ON Results.VariantGWAS((split_part(VARIANT_RECORD_PRIMARY_KEY, ':', 2)::BIGINT), VARIANT_RECORD_PRIMARY_KEY);


