SET MAINTENANCE_WORK_MEM="100GB";
--CREATE INDEX LD_RESULT_POPULATION ON Results.VariantLD USING BRIN(POPULATION_PROTOCOL_APP_NODE_ID);
--CREATE INDEX LD_RESULT_REFSNP ON Results.VariantLD USING GIN(VARIANTS array_ops);
CREATE INDEX LD_RESULT_LOCATION ON Results.VariantLD USING GIN(LOCATIONS array_ops);
--CREATE INDEX LD_RESULT_MAF ON Results.VariantLD USING GIN(MINOR_ALLELE_FREQUENCY array_ops);
