
/* DROP INDEX Results.FS_DATASET;
DROP INDEX Results.FS_BIN_INDEX;
DROP INDEX Results.FS_POSITION;*/

-- first two should be created w/table
--CREATE INDEX FS_DATASET ON Results.FeatureScore USING BRIN(PROTOCOL_APP_NODE_ID);
--CREATE INDEX FS_BIN_INDEX ON Results.FeatureScore USING GIST(BIN_INDEX);

CREATE INDEX FS_POSITION ON Results.FeatureScore USING GIST(BIN_INDEX, int8range(LOCATION_START, LOCATION_END, '[]'));
