DROP SCHEMA IF EXISTS CBIL;

CREATE SCHEMA IF NOT EXISTS CBIL;

GRANT USAGE ON SCHEMA CBIL TO gus_r, gus_w, comm_wdk_w;
ALTER DEFAULT PRIVILEGES IN SCHEMA CBIL GRANT SELECT ON TABLES TO gus_r;
ALTER DEFAULT PRIVILEGES IN SCHEMA CBIL GRANT SELECT ON SEQUENCES TO gus_r;
--ALTER DEFAULT PRIVILEGES IN SCHEMA CBIL GRANT SELECT ON MATERIALIZED VIEWS TO gus_r;
ALTER DEFAULT PRIVILEGES IN SCHEMA CBIL GRANT EXECUTE ON FUNCTIONS TO gus_r;

ALTER DEFAULT PRIVILEGES IN SCHEMA CBIL GRANT ALL ON TABLES TO gus_w;
ALTER DEFAULT PRIVILEGES IN SCHEMA CBIL GRANT ALL ON SEQUENCES TO gus_w;
ALTER DEFAULT PRIVILEGES IN SCHEMA CBIL GRANT ALL ON FUNCTIONS TO gus_w;
ALTER DEFAULT PRIVILEGES IN SCHEMA CBIL GRANT EXECUTE ON FUNCTIONS TO gus_w;
--ALTER DEFAULT PRIVILEGES IN SCHEMA CBIL GRANT ALL ON MATERIALIZED VIEWS TO gus_w;

INSERT INTO Core.DatabaseInfo
   (database_id, name, description, modification_date, user_read, user_write,
    group_read, group_write, other_read, other_write, row_user_id,
    row_group_id, row_project_id, row_alg_invocation_id)
SELECT nextval('core.databaseinfo_sq'), 'CBIL',
       'Application-specific data for the CBIL websites', now(),
       1, 1, 1, 1, 1, 1, 1, 1, p.project_id, 0
FROM (SELECT MAX(project_id) AS project_id FROM core.ProjectInfo) p
WHERE LOWER('CBIL') NOT IN (SELECT LOWER(name) FROM core.DatabaseInfo);
